mysite/apps/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

from . import views
import mysite.settings

import sys
sys.path.append("../")


app_name = 'apps'
urlpatterns = [
    # ログインページ
    path('', views.LoginView.as_view(), name="login"),
    # ログアウト
    path('logout/', views.Logout.as_view(), name='logout'),
    # 大学認証ページ
    path('university_register/', views.UniversityRegisterView.as_view(), name="university_register"),
    # ユーザー登録ページ
    path("user_register/",views.SignUpView.as_view(),name="signup"),
    # 商品一覧ページ
    path('index', views.IndexView.as_view(), name="index"),
    # 商品登録ページ
    path('product_create/', views.ProductCreateView.as_view(), name="product_create"),

# ------------------------以下未実装のルーティング------------------------------
    # path('myhistory/', views.MyhistoryView.as_view(), name="myhistory"),
    # path('mylist/', views.MylistView.as_view(), name="mylist"),
    # path('product_recreate/', views.ProductRecreateView.as_view(), name="product_recreate"),
    # path('product/', views.ProductView.as_view(), name="product"),
    # path('user_edit/', views.UserEditView.as_view(), name="user_edit"),
# ------------------------未実装のルーティングここまで--------------------------
    ]

# 画像をstaticから利用するための設定
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysite.settings.MEDIA_URL,document_root=mysite.settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]

mysite/apps/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>コレイル？</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header-9.css' %}" />
    <link rel="stylesheet" href="{% static 'css/progress_bar.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/product_image.css' %}" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="site-header"> <!-- https://github.com/shadeed/headers-css/blob/master/header-9.html#L15 -->
      <div class="wrapper site-header__wrapper">
        <div class="site-header__start">
          <a href="/index" class="brand""><img src="{% static 'logo.png' %}"></a>
        </div>
        {% block nav_bar %}
        {% endblock %}
      </div>
    </header>
    <script type="text/javascript" src="{% static 'js/header-9.js' %}"></script>
    {% block content %}
    {% endblock %}
  </body>
</html>

mysite/apps/templates/index.html
{% extends "header.html" %}
{% load static %}
{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/index" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a class="nav-link" href="{% url 'apps:logout' %}">ログアウト</a></li>

        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create" style="text-decoration: none;">出品</a>
    </div>
{% endblock %}
{% block content %}
  <nav class="navbar navbar-light bg-light">
    <!-- 検索機能-->
    <form class="form-inline" action="" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="何をお探しですか" value="{{query}}" name="q" aria-label="Search">
      <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name = "genre">
        <option selected disabled>カテゴリー選択</option>
        <!-- 分類の表示-->
        {% for i in genre %}
        <option value="{{i.genre_name}}">{{i.genre_name}}</option>
        {% endfor %}
      </select>
      <button class="btn" type="submit" value="送信" style="color: #fff; background-color: #2fa0f6; margin-left: 3vw;">検索</button>
    </form>
  </nav>
  <main>
    <!-- ユーザーの大学の出品中の商品を新着順で表示-->
    {% if item %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for i in item %}
    <div class="col">
      <div class="card h-100" href="/product">
        <img src="{% static i.icon %}" class="card-img-top" alt="商品画像">
        <div class="card-body">
          <h5 class="card-title">{{i.item_name}}</h5>
          <p>{{i.item_description}}</p>
          <form action="" method="POST">{% csrf_token %}
            <button class="detail_button" type="submit" name="item_id">詳細を見る</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="ui segment warning message">
      <p>検索結果はありません。</p>
    </div>
    {% endif %}

  </main>

{% endblock %}

mysite/apps/templates/login.html
{% extends "header.html" %}

{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">

          <li class="nav__item"><a href="/university_register" style="text-decoration: none;">新規登録</a></li>
        </ul>
      </nav>
    </div>
{% endblock %}

{% block content %}
  <main>

    <form action="" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group has-feedback">
          <p></p>
          {{ field }}
        </div>
      {% endfor %}
      <div class="row">

        {% for error in form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            <p>{{ error }}</p>
          </div>
        {% endfor %}
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </main>
{% endblock %}

mysite/apps/templates/myhistory.html
<!-- 未実装のページ -->

{% extends "header.html" %}

{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a href="/mylist" style="text-decoration: none;">出品一覧</a></li>
          <li class="nav__item"><a href="/user_edit" style="text-decoration: none;">アカウント</a></li>
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create" style="text-decoration: none;">出品</a>
    </div>
{% endblock %}

mysite/apps/templates/mylist.html
<!-- 未実装のページ -->

{% extends "header.html" %}

{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a href="/mylist" style="text-decoration: none;">出品一覧</a></li>
          <li class="nav__item"><a href="/user_edit" style="text-decoration: none;">アカウント</a></li>
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create" style="text-decoration: none;">出品</a>
    </div>
{% endblock %}

{% block content %}
  <main>
    <div class="row row-cols-1 row-cols-md-3 g-4">
    <!-- ユーザーの出品している商品を更新順で表示-->
    {% for i in item %} <!-- ユーザーの出品している商品のみを引っ張り出す方法がわからなかったです、、、-->
    <div class="card h-100">
      <img src="..." class="card-img-top" alt="商品画像">
      <div class="card-body">
        <h5 class="card-title">{{i.item_name}}</h5>
        <a href="/product_recreate" class="button">編集</a>
        <!-- 削除したらデータを消してリダイレクト-->
        <a href="/mylist" class="button" style="background-color: red;">削除</a>
        <!--bootsrapのmodalでconfirmationを出してもいいかもね -->
        <p class="card-text" style="margin-top: 10%;">最終更新日時：</p> <!-- 商品の更新日時をデータベースに追加して欲しいです。-->
      </div>
    </div>
    {% endfor %}
  </main>
{% endblock %}

mysite/apps/templates/product.html
<!-- 未実装のページ -->
{% extends "header.html" %}
{% load static %}

{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/index" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a class="nav-link" href="{% url 'apps:logout' %}">ログアウト</a></li>
          <!--<li class="nav__item"><a href="/mylist" style="text-decoration: none;">出品一覧</a></li>
          <li class="nav__item"><a href="/user_edit" style="text-decoration: none;">アカウント</a></li>-->
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create">出品</a>
    </div>
{% endblock %}
{% block content %}
      <p></p>
    <div id="image_info">
        <img id="mypic" src="{% static '線形代数.jpg' %}">
    <div id="item_info">
      <p class="product_name">チャート式シリーズ 大学教養 線形代数</p> <!-- item_nameお願いします -->
      <span class="category">カテゴリー</span>
      <span> 教科書</span> <!-- genre_nameお願いします -->
      <p></p>
      <span class="category">商品の状態</span>
      <span>目立った傷や汚れなし</span><!-- conditionの変数の名前わかりませんでした。。 -->
      <p></p>
      <div class="item_description">
        <span>経済学部1年生の必修の授業で使います。表面が少し汚れていますが、使用には問題ありません。</span> <!-- item_descriptionお願いします -->
      </div>
      <span class="category">　出品者　</span>
      <span class="seller_name">小坂 菜緒</span>
      <p></p>
      <button class="register_button" type="submit">　　　　　　　　　　連絡する　　　　　　　　　　</button>


    <script type="text/javascript" src="{% static 'js/product_image_slide.js' %}"></script>
  </main>
{% endblock %}

mysite/apps/templates/product_create.html
{% extends "header.html" %}
{% load static %}
{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/index" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a class="nav-link" href="{% url 'apps:logout' %}">ログアウト</a></li>
        </ul>
      </nav>
    </div>

{% endblock %}
{% block content %}
<main>
  <form method="post"  action = "" enctype="multipart/form-data">
    {% csrf_token %}
      <div id="dragDropArea">
          <div class="drag-drop-inside">
              <p class="drag-drop-buttons">
                  <input id="file_input" type="file" accept="image/*" value="ファイルを選択" name="icon" onChange="photoPreview(event)">
              </p>
              <p class="drag-drop-info">または、ドラッグ&ドロップ</p>
              <div id="previewArea"></div>
          </div>
      </div>

  <div class="item_info">
      <p class="item_name">商品名<br>
      <input id="area1" type="text" name="item_name" maxlength="40" onkeyup="product_name_str_len();">
      <div id="product_name_str_len">0/40文字</div></p>
      <p>商品の状態<br>
      <select name="condition" required>
        <option value="">選択してください</option>
        <option value="unused">新品、未使用</option>
        <option value="almost_new">未使用に近い</option>
        <option value="no_damage">目立った傷や汚れなし</option>
        <option value="low_damage">やや傷や汚れあり</option>
        <option value="middle_damage">傷や汚れあり</option>
        <option value="high_damage">全体的に状態が悪い</option>
      </select></p>
      <p>カテゴリー<br>
      <select name="category" required>
        <option value="default" disabled>選択してください</option>
        {% for i in genre%}
        <option value="{{i.genre_name}}">{{i.genre_name}}</option>
        {% endfor %}
      </select></p>
      <p>商品の説明<br>
      <textarea id="area2" name="item_description" cols="30" rows="3" maxlength="500" onkeyup="product_explanation_str_len();"></textarea>
      <div id="strLen">0/500文字</div></p>
      <button class="product_register_submit_button" type="submit" name="submit" value="出品">出品する</button>
      </div>
    </form>
  <script type="text/javascript" src="{% static 'js/product_image.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/count.js' %}"></script>

</main>
{% endblock %}

mysite/apps/templates/product_recreate.html
<!-- 未実装のページ -->

{% extends "header.html" %}
{% load static %}
{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a href="/mylist" style="text-decoration: none;">出品一覧</a></li>
          <li class="nav__item"><a href="/user_edit" style="text-decoration: none;">アカウント</a></li>
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create">出品</a>
    </div>
{% endblock %}
{% block content %}
<main>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
      <div id="dragDropArea">
          <div class="drag-drop-inside">
              <p class="drag-drop-buttons">
                  <input id="fileInput" type="file" accept="image/*" value="ファイルを選択" name="photo" onChange="photoPreview(event)">
              </p>
              <p class="drag-drop-info">または、ドラッグ&ドロップ</p>
              <div id="previewArea"></div>
          </div>
      </div>
      <!--
      <button class="register_button" type="submit" name="submit" value="登録">画像を登録</button>
      -->
  <div class="item_info">
      <p>商品名<br>
      {{ form.item_name }}
      <div id="product_name_str_len">0/40文字</div></p>
      <p>商品の状態<br>
      <select name="condition" required>
        <option value="" selected>aaa</option><!-- コンディションの変数（どれかわかりませんでした）お願いします あとplaceholderに変数を入れる方法がわからない。。-->
        <option value="unused">新品、未使用</option>
        <option value="almost_new">未使用に近い</option>
        <option value="no_damage">目立った傷や汚れなし</option>
        <option value="low_damage">やや傷や汚れあり</option>
        <option value="middle_damage">傷や汚れあり</option>
        <option value="high_damage">全体的に状態が悪い</option>
      </select></p>
      <p>カテゴリー<br>
      <select name="category" required>
        <option value="" selected>{{ genre_name }}</option> <!-- genre_nameお願いします -->
        <option value="text">教科書、参考書</option>
        <option value="furniture">家具</option>
        <option value="appliance">家電</option>
        <option value="bicycle">自転車</option>
        <option value="household_item">生活雑貨</option>
        <option value="others">その他</option>
      </select></p>
      <p>商品の説明<br>
      <textarea id="area2" name="comment" cols="30" rows="3" maxlength="500" onkeyup="product_explanation_str_len();" placeholder={{ item_description }} required></textarea> <!-- item_descriptionお願いします。あとplaceholderに変数を入れる方法がわからない。。 -->
      <div id="strLen">0/500文字</div></p>
      <button class="product_register_submit_button" type="submit" name="submit" value="更新">更新する</button>
      </div>

  <script type="text/javascript" src="{% static 'js/product_image.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/count.js' %}"></script>
</main>
{% endblock %}

mysite/apps/templates/university_register.html
{% extends "header.html" %}

{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/login.html" style="text-decoration: none;">ログイン</a></li>
        </ul>
      </nav>
    </div>
{% endblock %}

{% block content %}
  <main>
      <div class="Group">
        <div class="Group-Bar"></div>
          <div class="Group-Item isActive">
            <div class="Group-Item-CircleOuter Circle Shapeborder isActive">
            <div class="Group-Item-CircleInner Circle Shapeborder isActive"></div>
          </div>
          <p class="Group-Item-Text">大学認証</p>
        </div>
          <div class="Group-Item">
            <div class="Group-Item-CircleOuter Circle Shapeborder">
            <div class="Group-Item-CircleInner Circle Shapeborder"></div>
          </div>
          <p class="Group-Item-Text">ユーザー登録</p>
        </div>
        <div class="Group-Item">
          <div class="Group-Item-CircleOuter Circle Shapeborder">
            <div class="Group-Item-CircleInner Circle Shapeborder"></div>
            </div>
          <p class="Group-Item-Text">完了</p>
        </div>
      </div>
    </div>
    <div id="name_attention">名前を学生証（または合格証明証）に記載のとおり記入したのち、学生証（新入生の方は合格証明証）をアップロードしてください。</div>
    <form method="post" action = "{% url 'apps:university_register' %}" enctype="multipart/form-data" >
      {% csrf_token%}
          <div id="dragDropArea">
            <div class="drag-drop-inside">
                <p class="drag-drop-buttons">
                    <input id="fileInput" type="file" accept="image/*" value="ファイルを選択" name="image" onChange="photoPreview(event)">
                </p>
                <p class="drag-drop-info">または、ドラッグ&ドロップ</p>
                <div id="previewArea"></div>
           </div>
        </div>
        <div class="row">
        <div class="col">
            <p>姓</p>
            <input type="text" class="form-control" placeholder="Last name" aria-label="First name" name = "first" autocomplete="off">
        </div>
        <div class="col">
            <p>名</p>
            <input type="text" class="form-control" placeholder="First name" aria-label="Last name" name = "last" autocomplete="off">
        </div>
        </div>
        </p>
        <button class="register_button" type="submit" name="submit" value="登録">登録する</button>
    </form>
  </main>
{% endblock %}

mysite/apps/templates/user_edit.html
<!-- 未実装のページ -->

{% extends "header.html" %}
{% load static %}
{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/" style="text-decoration: none;">ホーム</a></li>
          <li class="nav__item"><a href="/mylist" style="text-decoration: none;">出品一覧</a></li>
          <li class="nav__item"><a href="/user_edit" style="text-decoration: none;">アカウント</a></li>
        </ul>
      </nav>
    </div>
    <div class="site-header__end">
      <a class="button" href="/product_create" style="text-decoration: none;">出品</a>
    </div>
{% endblock %}

{% block content %}
<main>
  <p>アイコン</p>
  <!--現在のアイコンを表示-->
  <img id="image_icon" src="../images/default_user.png">
  <form method="post" enctype="multipart/form-data">
      <div id="dragDropArea">
          <div class="drag-drop-inside">
              <p class="drag-drop-buttons">
                  <input id="fileInput" type="file" accept="image/*" value="ファイルを選択" name="photo" onChange="photoPreview(event)">
              </p>
              <p class="drag-drop-info">または、ドラッグ&ドロップ</p>
              <div id="previewArea"></div>
          </div>
      </div>
      <button class="register_button" type="submit" name="submit" value="登録">画像を登録</button>
  </form>
  <form method="post">
      <p>ニックネーム<br>
        <input id="area3" type="text" name="nickname" maxlength="40" onkeyup="nickname_str_len();" placeholder="{{user_name}}">
        <script type="text/javascript" src="{% static 'js/count.js' %}"></script>
        <div id="nickname_str_len">0/40文字</div></p>
      <label for="inputPassword5" class="form-label">パスワード</label>
      <input type="password" id="inputPassword2" class="form-control" aria-describedby="passwordHelpBlock" required autocomplete="off">

      <div id="passwordHelpBlock" class="form-text">
          8文字以上16文字以内で入力してください。
      </div>
      <label for="inputPassword5" class="form-label">パスワード（確認）</label>
      <input type="password" id="inputPassword2_confirm" class="form-control" aria-describedby="passwordHelpBlock" required onchange="CheckPassword_2();"  autocomplete="off">
      <script type="text/javascript" src="{% static 'js/confirm.js' %}"></script>
        <p>学部<br>
        <!-- ユーザーの大学の学部を表示(これは結局どうなったんだっけ)-->
        <select name="condition">
          <option value="">{{}}</option><!-- ユーザーの大学の学部をデータベースに作成できれば-->
          <option value="法学部">法学部</option>
          <option value="経済学部">経済学部</option>
          <option value="経営学部">経営学部</option>
          <option value="理学部">理学部</option>
          <option value="工学部">工学部</option>
        </select></p>
      <button class="button" type="submit" name="save" value="保存">保存</button>
  </form>
</main>
{% endblock %}}

mysite/apps/templates/user_register.html
{% extends "header.html" %}
{% load static %}
{% block nav_bar %}
    <div class="site-header__middle">
      <nav class="nav">
        <button class="nav__toggle" aria-expanded="false" type="button">
          menu
        </button>
        <ul class="nav__wrapper">
          <li class="nav__item"><a href="/login.html" style="text-decoration: none;">ログイン</a></li>
        </ul>
      </nav>
    </div>
{% endblock %}

{% block content %}
  <main>
    <div class="Group">
      <div class="Group-Bar"></div>
      <div class="Group-Item">
        <div class="Group-Item-CircleOuter Circle Shapeborder">
          <div class="Group-Item-CircleInner Circle Shapeborder"></div>
        </div>
        <p class="Group-Item-Text">大学認証</p>
      </div>
      <div class="Group-Item isActive">
        <div class="Group-Item-CircleOuter Circle Shapeborder isActive">
          <div class="Group-Item-CircleInner Circle Shapeborder isActive"></div>
        </div>
        <p class="Group-Item-Text">ユーザー登録</p>
      </div>
      <div class="Group-Item">
        <div class="Group-Item-CircleOuter Circle Shapeborder">
          <div class="Group-Item-CircleInner Circle Shapeborder"></div>
        </div>
        <p class="Group-Item-Text">完了</p>
      </div>
    </div>
<div class="row">
    <div class="col-sm-6">
        <br>
        <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field.label }}
                <br>
                {{ field }}
                <br>
                {{ field.errors }}
                <br>
            {% endfor %}
            <p></p>
            <button type="submit" class="user_button">登録</button>
        </form>
    </div>
</div>

  </main>
{% endblock %}